//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.17 at 11:50:24 PM UTC 
//


package sn.isi.m2gl.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sn.isi.m2gl.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sn.isi.m2gl.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCovid19InfoRequest }
     * 
     */
    public GetCovid19InfoRequest createGetCovid19InfoRequest() {
        return new GetCovid19InfoRequest();
    }

    /**
     * Create an instance of {@link GetCovid19InfoResponse }
     * 
     */
    public GetCovid19InfoResponse createGetCovid19InfoResponse() {
        return new GetCovid19InfoResponse();
    }

}
