//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.17 at 11:50:24 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.groupeisi.com")
package sn.isi.m2gl.wsdl;
